apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image
spec:
  template:
    spec:
      containerConcurrency: 10
      containers:
      - image: h2non/imaginary
        args: ["-enable-url-source"]
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
        env:
        - name: LOG_LEVEL
          value: debug
