apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: todo-app 
  namespace: default 
spec:
  template:
    spec:
      containerConcurrency: 10
      containers:
        - image: janakiramm/todo
